### ISSUE TITLE
Hi 👋

### ISSUE THREAD

**Issue by sammychinedu2ky** [guardrex/BlazorHostedWASM80#1]
This is just me trying to get your attention 😄. Please I wanna reach out to you via your email. Could you reply to me using my email -> sammychinedu2ky@gmail.com. Thanks 🙏

**Comment by guardrex** [comment]
Let's use the GH issue system for communication on Blazor subjects. I only use the email address that Aquent gave me for internal communication with Aquent and Microsoft. However, I just about live online 😩 (*I really should get out more!* 😄). I respond to GH issues on the docs repo very rapidly, sometimes within mere minutes.

**Comment by sammychinedu2ky** [comment]
@guardrex .. I'm don't wanna reach out based on Blazor . But something private. But if you're not okay sharing your mail, I would respect that as well. No pressure

**Comment by guardrex** [comment]
I'm not a "public" person, per se. I don't participate in social media or interact with the public outside of Blazor. I'm only here in a professional capacity on contract to Microsoft for Blazor doc work.

**Comment by sammychinedu2ky** [comment]
Okay thanks

**Comment by sammychinedu2ky** [comment]
Let me just state it here

**Comment by sammychinedu2ky** [comment]
Please do you have any dotnet roles or software roles available within your network. I don't mind sharing my CV here as well. Thanks

**Comment by guardrex** [comment]
I don't ... I'm just a contractor for Microsoft. I don't have anything to do with their hiring or any other outside firms.

**Comment by sammychinedu2ky** [comment]
Okay thanks. I appreciate 🙏
